voiceops:
  target: dev
  outputs:
    dev:
      type: postgres
      host: voiceops-silver.cdeykgc4iivg.ca-central-1.rds.amazonaws.com
      port: 5432
      user: voiceops
      password: testing_voiceops
      dbname: voiceops
      schema: public
      threads: 4